{% set name = "vertica_highcharts" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vertica-highcharts-{{ version }}.tar.gz
  sha256: c4ff8e022ac6dbe26231e448996d0cae3783820cca705894b08604429fd2ee5c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - jinja2
    - future

test:
  imports:
    - vertica_highcharts
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/vertica/vertica-highcharts
  summary: Python Highcharts wrapper
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - oualib
    - afard
